---
title: Ben Steers
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  resume:
    title: Resume
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: resume
  values:
    # education, work, projects, skills*
    organization: 
    organization_logo: 
    start_date: 
    end_date: 
    images:
    # education
    courses:
      - title: 
        description: 
        is_featured: 
    # projects
    report: 

subtitle: 
email: ben@bensteers.me
description: Data Science, Acoustics, Web Development.
url: 
city: Brooklyn
state: NY
logo: "/uploads/logo3.png"
tiles_source: resume
tiles_categories:
- education
tiles_count: 6
github_url: https://github.com/bensteers/
