---
title: Ben Steers
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  resume-item:
    title: Resume Item
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: resume-item
  values:
    organization: 
    organization_logo: 
    start_date: 
    end_date: 
subtitle: 
email: ben@bensteers.me
description: Data Science, Acoustics, Web Development.
url: 
city: Brooklyn
state: NY
tiles-source: posts
tiles-count: 6
github_url: https://github.com/bensteers/
logo: "/uploads/logo3.png"
