---
title: Ben Steers
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  resume-item:
    title: Resume Item
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: 
email: ben@bensteers.me
description: A responsive site template designed by HTML5 Up<br /> and released under
  the Creative Commons.
url: 
city: Brooklyn
state: NY
tiles-source: resume-item
tiles-count: 6
github_url: https://github.com/bensteers/

defaults:
  - scope:
      path: ""
      type: resume-item
    values:
      organization: 
      organization_logo: 
      start_date:
      end_date: 